Enhance VanillaRenderer customizable class names
eclipsesource/jsonforms pull request #1679
Opened 2021-01-19 17:04 UTC by TheZoker

Fixes #1677

- Change order of classnames for layouts
- Allow customization of the validation class
- Add class to validation element even if no error occurs

2021-01-20 09:08 UTC, lucas-koehler requested changes
Implementation looks good to me.

Just add the new `control.validation` style definition to the Styles.md documentation, please :)

2021-01-20 11:23 UTC, sdirix requested changes
Regarding the error class: I think we should either consistently hard code the error class or make all of them configurable. @lucas-koehler what do you think?

2021-01-20 11:29 UTC, lucas-koehler commented
> Regarding the error class: I think we should either consistently hard code the error class or make all of them configurable. @lucas-koehler what do you think?

While we're already at it I think we should make it configurable. I imagine this could be useful when using some kind of theme.

2021-01-20 13:49 UTC, lucas-koehler approved these changes

2021-01-22 11:46 UTC, sdirix approved these changes

2021-01-22 11:47 UTC, merged