Add Material renderer for anyOf const array
eclipsesource/jsonforms pull request #1709
Opened 2021-03-01 17:23 UTC by AlexandraBuzila

Render an anyOf array of consts as a list of checkboxes. The checkbox is
checked if the array item it represents is present in the data.

2021-03-01 19:27 UTC, sdirix requested changes
In general I like it very much. However there are some things I would like to see differently.

Currently the schema tested for looks like this
```js
"property": {
  "type": "array",
  "items": {
    "anyOf": [
      { },
    ]
  },
},
 ```
 which doesn't really fit to the use case:

- The schema allows the same entry multiple times, but our control only handles them uniquely (the control therefore misbehaves if the same entry is there multiple times)
- `anyOf` stands for that **at least** one item matches. However we're handling it like "enums", which are unique. So it should be `oneOf`.
- To be consistent with our other `oneOfEnum` controls we should check whether the `items` are `oneOf` and contain a `const` in each entry.
- Ideally we should also be able to handle `enum` content

I would prefer to support the following schemas:
```js
"property": {
  "type": "array",
  "items": {
    "oneOf": [
      {
        "const": <any>,
        "title": "mylabel"
      },
    ]
  },
  "uniqueItems": true
},
```
and
```js
"property": {
  "type": "array",
  "items": {
    "type": "string",
    "enum": ["a", "b", "c"]
  },
  "uniqueItems": true
},
```

So we check for

 - type array with unique items
 - the items are either `enum` or `oneOf` containing `const`
 
 ---
 
 Please also add an example to the example app.

2021-03-01 19:27 UTC, sdirix commented on packages/material/src/complex/MaterialEnumArrayControl.tsx
> +export default MaterialEnumArrayControl;
To be consistent with other controls we should default export the wrapped version

2021-03-01 19:27 UTC, sdirix commented on packages/material/src/index.ts
> +    renderer: withJsonFormsControlProps(MaterialEnumArrayControl)
Don't wrap here, but use the already wrapped imported version

2021-03-01 19:27 UTC, sdirix commented on packages/material/src/complex/MaterialEnumArrayControl.tsx
> +                id={option.const}
Careful: The value of `const` can be anything! It doesn't need to be a string, but could for example be an `object`, `array`, etc. Please see `mapStateToOneOfEnumProps` where we already had to handle the case.

2021-03-01 19:27 UTC, sdirix commented on packages/material/src/complex/MaterialEnumArrayControl.tsx
> +  };
If you would use `withJsonFormsArrayControlProps` you would get functions to add and remove items to the array for free, i.e. `addItem`, `removeItems`, `moveUp` and `moveDown` would get injected. `schema` would also already point to the `items` object.

2021-03-02 07:37 UTC, sdirix requested changes
Additionally it would be great when we don't add all the logic into the renderer. Instead I would prefer a new `mapStateToMultiEnumProps` and `mapDispatchToMultiEnumProps`.

- `mapStateToMultiEnumProps`: extracting the `items` options from `oneOf` or `enum`, similar to `mapStateToEnumPros` and `mapStateToOneOfEnumProps`
- `mapDispatchToMultiEnumProps`: providing a `addItem` and `removeItem` function which can be used for toggling. Using this we can also remove the `useRef` workaround

By extracting the logic from the renderer we can easily write a multi-select enum with a different renderer (e.g. Material UI's multi select dropdown) as well as more easily add the same renderer in the other renderer sets too.

2021-03-05 15:39 UTC, AlexandraBuzila commented
I updated the commit to include you comments, Stefan. The renderer now supports both `oneOf` and `enum` items.

2021-03-10 08:10 UTC, sdirix requested changes
Looks good!

2021-03-10 08:23 UTC, sdirix approved these changes

2021-03-10 08:25 UTC, merged