Add material ui support for rendering select lists in cells based on …
eclipsesource/jsonforms pull request #1758
Opened 2021-05-26 05:36 UTC by ryan-bennett

Add material ui support for rendering select lists in cells based on oneOf schema definitions.

2021-05-26 05:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/eclipsesource/jsonforms?pullRequest=1758) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/eclipsesource/jsonforms?pullRequest=1758) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/eclipsesource/jsonforms?pullRequest=1758) it.</sub>

2021-05-26 12:27 UTC, sdirix commented
Hi @ryan-bennett, thank you very much for the contribution :heart:  We'll have a look at it soon!

However, please remove the changes to the `package-lock.json` from your PR.

2021-05-27 01:56 UTC, ryan-bennett commented
Thanks Stefan, removed the changes to the package-lock.

2021-06-10 09:40 UTC, sdirix requested changes
Looks good! I only have some minor comments.

Please adapt your commit message. For example you can change it to:

```
Add React Material oneOf enum cell

Also includes example and test cases.
```

Please also add an example in the `examples` package. You can just add an `enumInArray.ts` file with the following content:

```ts
import { registerExamples } from './register';

export const schema = {
  type: 'array',
  items: {
    type: 'object',
    properties: {
      plainEnum: {
        type: 'string',
        enum: ['foo', 'bar']
      },
      oneOfEnum: {
        type: 'string',
        oneOf: [
          { const: 'foo', title: 'Foo' },
          { const: 'bar', title: 'Bar' },
          { const: 'foobar', title: 'FooBar' }
        ]
      },
    }
  }
};

export const uischema = {
  type: 'VerticalLayout',
  elements: [
    {
      type: 'Control',
      scope: '#'
    }
  ]
};

export const data: any[] = [];

registerExamples([
  {
    name: 'enumInArray',
    label: 'Array containing enums',
    data,
    schema,
    uischema
  }
]);
```
Don't forget to also add it to the `index.ts` ;).

2021-06-10 09:40 UTC, sdirix commented on packages/react/src/JsonFormsContext.tsx
> +    // @ts-ignore
Is this needed?
```suggestion
```

2021-06-10 09:40 UTC, sdirix commented on packages/react/src/JsonFormsContext.tsx
> +    ({ctx, props}: JsonFormsStateContext & EnumCellProps) => {
```suggestion
    ({ ctx, props }: JsonFormsStateContext & EnumCellProps) => {
```

2021-06-10 09:40 UTC, sdirix commented on packages/material/src/cells/MaterialOneOfEnumCell.tsx
> + * Default tester for enum controls.
```suggestion
 * Default tester for oneOf enum controls.
```

2021-06-10 09:40 UTC, sdirix commented on packages/material/test/renderers/MaterialOneOfEnumCell.test.tsx
> +          }
Can't we simplify this?

```suggestion
          country: schema
```

2021-06-24 00:49 UTC, ryan-bennett commented
Hi Stefan, I think I have processed all of the requested changes. Thanks for walking me though the process.

2021-06-24 05:58 UTC, sdirix approved these changes
LGTM

2021-06-24 06:05 UTC, merged

2021-06-24 07:25 UTC, sdirix commented
@ryan-bennett 
JSON Forms `3.0.0-alpha.0` is now released containing the oneOf enum cell renderer. You can consume it by referring to the concrete version or simply use the `next` tag, for example `npm install @jsonforms/core@next @jsonforms/react@next @jsonforms/material-renderers@next`.

Thank you again for the contribution :)