Register RadioGroupControl in React Vanilla
eclipsesource/jsonforms pull request #1791
Opened 2021-07-27 15:35 UTC by max-elia

- Register RadioGroupControl and radioGroupControlTester
- Convert enum and oneOfEnum to same format
- Create Test for oneOfEnum
Closes #1783

Signed-off-by: Max Elia Schweigkofler <max_elia@hotmail.de>

2021-08-02 03:05 UTC, max-elia commented
@LukasBoll

2021-08-04 08:31 UTC, LukasBoll approved these changes

2021-08-13 07:58 UTC, sdirix requested changes
The code works, however the bindings should be constructed slightly differently. We'll let the core framework do the `options` calculation and bind correspondingly.

2021-08-13 07:58 UTC, sdirix commented on packages/vanilla/src/controls/RadioGroup.tsx
> +      );
This manual computation is not necessary, we offer specific bindings for this, i.e. `withJsonFormsEnumControlProps` and `withJsonFormsOneOfEnumProps`. The bindings eventually call [mapStateToEnumControlProps](https://github.com/eclipsesource/jsonforms/blob/ba6bdc5a93044a872285cd71ed40d9a54f437561/packages/core/src/util/renderer.ts#L457-L470) or [mapStateToOneOfEnumControlProps](https://github.com/eclipsesource/jsonforms/blob/ba6bdc5a93044a872285cd71ed40d9a54f437561/packages/core/src/util/renderer.ts#L478-L490) which do this mapping for you and will hand them over as `options` prop.
```suggestion
```

2021-08-13 07:58 UTC, sdirix commented on packages/vanilla/src/controls/OneOfRadioGroupControl.tsx
> +export default withVanillaControlProps(withJsonFormsControlProps(OneOfRadioGroupControl));
```suggestion
export default withVanillaControlProps(withJsonFormsOneOfEnumProps(OneOfRadioGroupControl));
```

2021-08-13 07:58 UTC, sdirix commented on packages/vanilla/src/controls/RadioGroupControl.tsx
> +export default withVanillaControlProps(withJsonFormsControlProps(RadioGroupControl));
```suggestion
export default withVanillaControlProps(withJsonFormsEnumProps(RadioGroupControl));
```

2021-09-14 07:26 UTC, max-elia commented on packages/vanilla/src/controls/RadioGroupControl.tsx
> +export default withVanillaControlProps(withJsonFormsControlProps(RadioGroupControl));
Thanks, implemented the changes.

2021-10-04 11:25 UTC, sdirix commented on packages/vanilla/test/renderers/RadioGroupControl.test.tsx
> +        //expect(radioButtons).toHaveLength(3);
```suggestion
        expect(radioButtons).toHaveLength(3);
```

2021-10-04 12:07 UTC, sdirix approved these changes
Rebased on latest master. Works as expected!

2021-10-04 14:28 UTC, merged