Update MUI to version 5
eclipsesource/jsonforms pull request #1812
Opened 2021-10-04 12:21 UTC by TheZoker

Closes #1805

- Update material ui to version 5
- Replace `@material-ui/pickers` with `@mui/lab` pickers
- Update enzym adapter to version 17

2021-11-16 16:04 UTC, LukasBoll reviewed
Code is looking good to me!
I checked all the examples, there is just one issue with the Categorization.
The label of the selected tap/category is not visible in the header.

2021-11-23 09:50 UTC, TheZoker commented
Should be fixed:

![image](https://user-images.githubusercontent.com/1368405/143002833-d4fd8936-9f8b-43b6-b303-b76ea9da1558.png)

2021-12-02 16:35 UTC, sdirix requested changes
Works great for me! Thanks for the work.

I have just minor feedback, see my comments.

2021-12-06 14:47 UTC, sdirix commented on packages/material/package.json
> +    "@mui/material": "^5.2.2"
Do we really depend on the latest versions of all these frameworks? If 5.0.0 is good enough then we should indicate as such to not force users to upgrade from 5.1 to 5.2 for example when we don't actually require them to.

2021-12-07 07:49 UTC, sdirix approved these changes
LGTM. Thanks for the great work!

2021-12-07 07:52 UTC, merged