Remove redux example
eclipsesource/jsonforms pull request #1828
Opened 2021-11-02 16:26 UTC by TheZoker

Current status:

| Example | Working | Broken before | Comment |
|---|:---:|:---:|---|
| 1169 | ✅ |  |  |
| 1220 | ❌ |  | No action buttons (and logic) |
| 1273 | ✅ |  |  |
| 1713 | ✅ |  |  |
| allOf | ✅ |  |  |
| anyOf | ✅ |  |  |
| anyOf_simple | ✅ |  |  |
| oneOf | ✅ |  |  |
| 1265_array | ✅ | ✅ |  |
| 1265_object | ✅ |  |  |
| 1265_simple | ✅ |  |  |
| 1273_simple | ✅ |  |  |
| oneOfArray | ✅ |  |  |
| anyOf-oneOf-allOf-resolve | ✅ | ✅ |  |
| array | ❌ |  | No action buttons (and logic) |
| nestedArray | ❌ |  | No action buttons (and logic) |
| person | ✅ |  |  |
| array-with-detail | ✅ |  |  |
| array-with-detail-and-rule | ✅ |  |  |
| array-with-custom-element-label | ✅ |  |  |
| stringArray | ✅ |  |  |
| categorization | ✅ |  |  |
| categorizationstepper | ✅ |  |  |
| categorizationsteppernavbuttons | ✅ |  |  |
| control-options | ✅ |  |  |
| day1 | ✅ |  |  |
| day2 | ✅ |  |  |
| day3 | ✅ |  |  |
| day4 | ✅ |  |  |
| day5 | ✅ |  |  |
| day6 | ❌ | ✅ | No action buttons (Current version: No custom rating control) |
| dates | ✅ |  |  |
| dynamic | ✅ |  |  |
| generate | ✅ |  |  |
| generate-ui | ✅ |  |  |
| layout-vertical | ✅ |  |  |
| layout-horizontal | ✅ |  |  |
| layout-group | ✅ |  |  |
| layout-complex | ✅ |  |  |
| rule | ✅ |  |  |
| rule-enable | ❌ |  | No action buttons (and logic) |
| resolve | ❌ |  | Cannot resolve schema |
| configDefault | ✅ |  |  |
| configCustom | ✅ |  |  |
| text | ✅ |  |  |
| numbers | ✅ |  |  |
| scope | ✅ |  |  |
| list-with-detail | ✅ | ✅ |  |
| list-with-detail-no-labelref | ✅ | ✅ |  |
| list-with-detail-registered | ✅ | ✅ |  |
| rootObject | ✅ |  |  |
| object | ✅ |  |  |
| i18n | ❌ |  | No action buttons (and logic) |
| issue-1253 | ✅ |  |  |
| issue-1253-wrong-path-binding | ✅ |  |  |
| issue-1253-cell-missing-cell | ✅ | ✅ | |
| issue-1253-add-button-empty-row | ✅ | ✅ | |
| issue-1253-enum-error | ✅ | ✅ |  |
| issue-1254 | ✅ |  |  |
| oneOf-recursive | ✅ |  |  |
| huge | ✅ | ✅ |  |
| default | ✅ |  |  |
| onChange | ✅ |  |  |
| enum | ✅ |  | No action buttons (and logic) |
| radio-group | ✅ |  |  |
| booleanToggle | ✅ |  |  |
| multi-enum | ✅ |  |  |
| enumInArray | ✅ |  |  |
| Readonly Fields | ✅ |  |  |
| 1779-string | ❌ | ✅ | No applicable renderer found |
| 1779-number | ❌ | ✅ | No applicable renderer found |
| ifthenelse | ✅ |  |  |

2021-12-06 12:41 UTC, LukasBoll requested changes
Overall Code looks good and the examples themselves are behaving well, but there are some problems when changing between examples, e.g.:
Changing from “oneOf (in Array)” to “array”: No appliciable renderer is found.
Changing from “Date” to ”DynamicChange”: The old Schema from Date is used.

2021-12-06 12:41 UTC, LukasBoll commented on packages/examples/src/example.ts
> +  actions?: any;
I think we can add these types here.
```suggestion
  actions?: {label: string, apply: (props: StateProps) => any}[];
```

2021-12-06 12:41 UTC, LukasBoll commented on packages/example/src/App.tsx
> +              {actions?.map((buttons: any, index: number) => (
I think this should be `button`

2021-12-06 12:41 UTC, LukasBoll commented on packages/examples/src/examples/ruleInheritance.ts
> +  [
Currently the actions of ruleInheritance aren’t working. I think you added one pair of braces to many.
```suggestion
```

2021-12-06 13:51 UTC, TheZoker commented
Thanks for the review! Yes you are right, there seems to be an issue when switching examples. I'll have to investigate this further

2021-12-07 09:04 UTC, LukasBoll approved these changes
Looks good to me, thank you!

2021-12-10 07:53 UTC, sdirix approved these changes
LGTM! Thanks!

2021-12-10 07:54 UTC, merged