Add readonly type to renderers prop in JsonForms.vue
eclipsesource/jsonforms pull request #1860
Opened 2021-12-23 04:33 UTC by rokiyama

Fix #1859

This PR adds the readonly type to `renderers` props in JsonForms.vue.

According to the README of jsonforms/vue, `renderers` may be the value of `Object.freeze`. So it might be better that `renderers` also accept readonly types.

2021-12-23 04:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/eclipsesource/jsonforms?pullRequest=1860) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/eclipsesource/jsonforms?pullRequest=1860) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/eclipsesource/jsonforms?pullRequest=1860) it.</sub>

2022-01-03 09:52 UTC, sdirix requested changes
Hi @rokiyama, thank you very much for the contribution! :heart: 

Your PR solves the issue for the `renderers` but it would be even nicer if it could be solved for the remaining registries too.

I would like to suggest introducing a `MaybeReadonly` type, e.g.

```
type MaybeReadonly<T> = T | Readonly<T>;
```

and using that for the props `renderers`, `cells` and `uischemas`

2022-02-08 06:21 UTC, rokiyama commented
@sdirix Sorry for my late reply. I read your commit 5b985849c08915f0005abfcc9ea95b33ecb70944 , it would help me if this change is merged.

2022-04-07 11:29 UTC, sdirix approved these changes
Tested and fixed the type issue when using the Volar VS Code extension

2022-04-07 11:32 UTC, merged