Add special className to style boolean cells (checkbox) in Vanilla package
eclipsesource/jsonforms pull request #1865
Opened 2022-01-10 12:04 UTC by andresgutgon

# What?
Hi I was using the lib and I noticed Vanilla React has the same styles for `input type='text'` and `input type='checkbox'`. Would be possible to have different styles? This way is easier to style it

Thanks!

2022-01-11 10:55 UTC, sdirix commented
Thanks for the contribution, we'll take a look very soon! :heart:

2022-01-11 11:04 UTC, andresgutgon commented
Nice! Thanks @sdirix what do you think about the order of `label/input` when is a boolean/checkbox?

2022-01-11 12:43 UTC, sdirix commented
> Nice! Thanks @sdirix what do you think about the order of `label/input` when is a boolean/checkbox?
> 
> At the moment only added the class to style the checkbox. But the order remains the same as with `input`

Can you point me to some occurrences where the input is defined within a label? I'm not aware of that pattern. The [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox) also doesn't showcase it.

2022-01-11 12:43 UTC, sdirix requested changes
Can you take a look at the failing test cases?

2022-01-13 12:40 UTC, andresgutgon commented
> Can you point me to some occurrences where the input is defined within a label?

Uhmm maybe is just me. I always do checkbox/radio this way. But maybe is not something standard. Feel free to ignore.

2022-01-13 12:42 UTC, andresgutgon commented
I think I fixed the specs, let me know if it works. Thanks!

2022-01-13 13:27 UTC, sdirix approved these changes
LGTM!

2022-01-13 14:35 UTC, merged

2022-01-13 14:36 UTC, sdirix commented
Thanks again for the contribution ;)