Don't modify user-schemas in Material Object Renderer
eclipsesource/jsonforms pull request #1871
Opened 2022-01-15 14:26 UTC by LukasBoll

Don't modify user-schemas in Material Object Renderer

closes #1712

Signed-off-by: Lukas Boll lukas-bool@web.de

2022-01-21 09:49 UTC, max-elia approved these changes
The changes LGTM.
Tested it and it works as expected.

2022-01-21 09:49 UTC, max-elia commented on packages/material/src/complex/MaterialObjectRenderer.tsx
> +        ()=>Generate.uiSchema(schema, 'Group',undefined,undefined,label),
I suggest a consistent use of spaces.
```suggestion
        () => Generate.uiSchema(schema, 'Group', undefined, undefined, label),
```

2022-01-21 09:49 UTC, max-elia commented on packages/core/src/generators/uischema.ts
> +    generateUISchema(jsonSchema, [], prefix, '', layoutType, rootSchema,label),
```suggestion
    generateUISchema(jsonSchema, [], prefix, '', layoutType, rootSchema, label),
```
Consistent spacing

2022-01-24 20:22 UTC, LukasBoll commented
Thanks! I updated the code accordingly.

2022-02-01 09:39 UTC, sdirix requested changes

2022-02-01 09:39 UTC, sdirix commented on packages/core/src/generators/Generate.ts
> +    label?: string
Can we remove this again?

2022-02-01 09:39 UTC, sdirix commented on packages/material/src/complex/MaterialObjectRenderer.tsx
> +        () => Generate.uiSchema(schema, 'Group', undefined, undefined, label),
I would prefer assigning the label as part of the generator

2022-02-22 08:37 UTC, sdirix commented on packages/material/src/complex/MaterialObjectRenderer.tsx
>      detailUiSchema.type = 'VerticalLayout';
We should also remove this modification ;)

2022-03-29 08:57 UTC, sdirix commented on packages/core/src/reducers/reducers.ts
> + * @param fallback the type of the layout to use or a schema-generator function
```suggestion
 * @param fallback the type of the layout to use or a UI-schema-generator function
```

2022-03-29 08:57 UTC, sdirix commented on packages/material/src/complex/MaterialObjectRenderer.tsx
> +        () =>  {return isEmpty(path)?Generate.uiSchema(schema, 'VerticalLayout'):{...Generate.uiSchema(schema, 'Group'), label: label}},
```suggestion
        () => isEmpty(path) ? Generate.uiSchema(schema, 'VerticalLayout') : {...Generate.uiSchema(schema, 'Group'), label},
```

2022-03-29 08:57 UTC, sdirix commented on packages/material/src/complex/MaterialObjectRenderer.tsx
>      [uischemas, schema, uischema.scope, path, uischema, rootSchema]
When the label changes we might need to generate a new UI Schema, therefore the label needs to be added to the dependency array
```suggestion
    [uischemas, schema, uischema.scope, path, label, uischema, rootSchema]
```

2022-04-02 17:03 UTC, LukasBoll commented
Thank you, I added your suggestion!

2022-04-06 10:38 UTC, sdirix approved these changes

2022-04-06 11:09 UTC, merged