Update readmes for 3.0
eclipsesource/jsonforms pull request #1875
Opened 2022-01-24 22:12 UTC by LukasBoll

Update readmes for 3.0
added link to migrationguide

closes #1852

Signed-off-by: Lukas Boll lukas-bool@web.de

2022-04-07 14:07 UTC, sdirix requested changes
Looks good overall. Please take care of the comments ;)

2022-04-07 14:07 UTC, sdirix commented on packages/vue/vue-vanilla/README.md
> +      renderers: Object.freeze(vanillaRenderers),data: {
```suggestion
      renderers: Object.freeze(vanillaRenderers),
      data: {
```

2022-04-07 14:07 UTC, sdirix commented on packages/vue/vue/README.md
> +These bindings handle the props given to the `dispatch-renderer` and use the JSON Forms Core to determine specialized inputs for many use cases like validation and rule-based visibility. This way it´
```suggestion
These bindings handle the props given to the `dispatch-renderer` and use the JSON Forms Core to determine specialized inputs for many use cases like validation and rule-based visibility.
Using these bindings as a basis it's straightforward to create renderer sets for Vue 3.
```

2022-05-27 09:33 UTC, lucas-koehler reviewed
LGTM overall. I have some very minor remarks.

In the root README line 12, I would replace
> 2. Install dependencies with `npm ci` (or `npm install` when using an older version)

with:

> 2. Install dependencies with `npm ci`

As the JSONForms build does not work with node versions older than 14 (which includes npm 6), JSONForms cannot be built with an npm version not supporting the `ci` command

2022-05-27 09:33 UTC, lucas-koehler commented on packages/vue/vue/README.md
> +Using these bindings as a basis it's straightforward to create renderer sets for Vue 3.
```suggestion
Using these bindings as a basis, it's straightforward to create renderer sets for Vue 3.
```

2022-05-27 09:33 UTC, lucas-koehler commented on packages/vue2/vue2/README.md
> +Using these bindings as a basis it's straightforward to create renderer sets for Vue 2.
```suggestion
Using these bindings as a basis, it's straightforward to create renderer sets for Vue 2.
```

2022-06-16 19:06 UTC, sdirix approved these changes

2022-06-16 19:09 UTC, merged