(vue) add binding for one enum cell elements
eclipsesource/jsonforms pull request #1919
Opened 2022-04-15 09:23 UTC by jdwit

The control bindings for Vue where missing the one for cells with a `oneOf` schema; no `options` prop was generated. For control bindings this is present, this PR adds the binding for cells. If you have any feedback please let me know, I would like to contribute more in the future since we are investing in this project for our application that will soon be in production.

2022-04-15 09:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/eclipsesource/jsonforms?pullRequest=1919) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/eclipsesource/jsonforms?pullRequest=1919) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/eclipsesource/jsonforms?pullRequest=1919) it.</sub>

2022-04-26 15:42 UTC, yaffol commented
Just a note in case it's helpful to you - there is also a Vue/Vuetify renderer set in development (though usable now) over at https://github.com/eclipsesource/jsonforms-vuetify-renderers

2022-04-27 12:14 UTC, sdirix requested changes
Hi @jdwit,

Thank you very much for the PR! In general we're definitely interested in any improvements to our bindings and renderers. If you want to tackle something which requires more effort and you want to be certain that we'll actually merge it, I would like to recommend to open a feature request first, describe your planned implementation and wait for our feedback.

However things like this which is just a missing binding certainly don't require a previous discussion ;)

2022-04-27 12:14 UTC, sdirix commented on packages/vue/vue/src/jsonFormsCompositions.ts
> +      mapStateToOneOfEnumControlProps,
There is a different mapping for cells, so this should be `mapStateToOneOfEnumCellProps`

2022-05-09 08:40 UTC, sdirix approved these changes
LGTM! Thanks!

2022-05-09 08:41 UTC, merged