Integrate external errors in form
eclipsesource/jsonforms pull request #1937
Opened 2022-05-19 14:23 UTC by AlexandraBuzila

Add support for specifying external errors via `additionalErrors:
ajv.ErrorObject[]` prop.

The additional errors are merged with the validation errors and are
supplied to the affected controls. The additional errors are not
affected by the validationMode like the validation errors are and it is
the responsability of the framework user to update the prop when
applicable (e.g. on ValidationMode changes).

Fixes #1926

Contributed on behalf of STMicroelectronics

2022-05-20 12:46 UTC, sdirix requested changes
Looks good already!

Can you add an example to the example app which adds/removes multiple additional errors on the click of a button?

2022-05-20 12:46 UTC, sdirix commented on packages/core/src/reducers/core.ts
> +  return errorsAt(instancePath, schema, matchPath)(state.validationMode === 'ValidateAndHide' ? [...additionalErrors] : [...errors, ...additionalErrors]);
```suggestion
  return errorsAt(instancePath, schema, matchPath)(state.validationMode === 'ValidateAndHide' ? additionalErrors : [...errors, ...additionalErrors]);
```

2022-05-20 15:47 UTC, AlexandraBuzila commented
Thank you for the review, Stefan! I updated the code and added examples for React (material and vanilla) and vue-vanilla. The contributed example should work with the angular examples as well when they'll support displaying buttons for the contributed actions like the React app (it's currently not the case).

2022-05-23 08:27 UTC, sdirix approved these changes
Great! Thank you!

2022-05-23 08:39 UTC, merged