added control for the arrayRenderer, consolidate module, added styles
eclipsesource/jsonforms pull request #2011
Opened 2022-08-25 07:09 UTC by rsoika

also removed the file ArrayControl tsx and consolidated in ArrayControlRenderer.tsx

2022-08-25 19:45 UTC, rsoika commented
This is the new layout example:

![image](https://user-images.githubusercontent.com/1339124/186754400-9fd167ae-f154-4d04-b1fb-489319c9e85f.png)

2022-09-04 20:13 UTC, rsoika commented
Hi @sdirix  I don't want to be impatient, but what did you think about my last pull request?

2022-09-05 09:54 UTC, sdirix commented
Hi @rsoika, we'll take a look :+1:

2022-09-05 11:15 UTC, lucas-koehler requested changes
Hi @rsoika ,
thank you very much for your pull request. In general, this already works great. I tested the changes with the vanilla dev example and did not run into any issues.

I added some comments regarding formatting and I think we should still export the `ArrayControl` to allow adopters to use it in their custom renderers and to not break the API in this regard.

2022-09-05 11:15 UTC, lucas-koehler commented on packages/vanilla/src/styles/styles.ts
> +  },
Please remove the whitespace following the comma

2022-09-05 11:15 UTC, lucas-koehler commented on packages/vanilla/src/complex/array/index.ts
> +export {  ArrayControlRenderer };
Similarily to the comment in `ArrayControlRenderer.tsx`, I think we should export `ArrayControl` here.
You can get import it together with the `ArrayControlRenderer` like this:
`import ArrayControlRenderer, { ArrayControl } from './ArrayControlRenderer';`
and the change the export to
`export {  ArrayControlRenderer, ArrayControl };`

2022-09-05 11:15 UTC, lucas-koehler commented on packages/vanilla/src/complex/array/ArrayControlRenderer.tsx
> +              <div key={index}><JsonFormsDispatch
Please add a new line before `<JsonFormsDispatch` to increase readability

2022-09-07 13:00 UTC, rsoika commented
Hi @lucas-koehler, I have fixed now the issues you mentioned.

2022-09-08 07:11 UTC, lucas-koehler approved these changes
@rsoika Thank you for the updates and thanks again for your contribution. LGTM now :)

2022-09-08 07:12 UTC, merged