Fix/datepicker validation
eclipsesource/jsonforms pull request #2200
Opened 2023-10-27 11:35 UTC by LukasBoll

Set value to 'undefined' if the text input is empty. If the input is 
invalid, set the actual value instead of "invalid data" and display the 
last input instead of an empty field.

Closes #2183

2023-10-31 09:41 UTC, sdirix commented
New behavior:
 - During editing, when value is a valid date/time, immediately write through
 - During editing, when value is not valid, don't trigger any change
 - On blur, if value is not valid, write `undefined` in data

2023-11-13 22:07 UTC, sdirix requested changes
In principal looks good, however I found some issues in the code. Please also test the exceptional cases for which we require all that custom blur update handling.

2023-11-13 22:07 UTC, sdirix commented on packages/material-renderers/src/controls/MaterialDateControl.tsx
> +  };
Whenever the new value of a state depends on the old value, the functional updater should be used, i.e. `const updateChild = () => setKey((key) => key + 1)`

2023-11-13 22:07 UTC, sdirix commented on packages/material-renderers/src/controls/MaterialDateControl.tsx
> +  );
This `useMemo` will never work as `updateChild` is a new instance on every `render` call, therefore always breaking the memo.

2023-11-13 22:07 UTC, sdirix commented on packages/material-renderers/src/controls/MaterialDateControl.tsx
> +  const [key, setKey] = useState<any>(0);
We should avoid `any` at all cost and only use it when there is no better way. Here we can just type as `number`.

2023-11-13 22:07 UTC, sdirix commented on packages/material-renderers/src/controls/MaterialDateTimeControl.tsx
> +  const [key, setKey] = useState<any>(0);
The `key` here is never used

2023-11-13 22:07 UTC, sdirix commented on packages/material-renderers/src/controls/MaterialTimeControl.tsx
> +  const [key, setKey] = useState<any>(0);
The `key` here is never used

2023-11-13 22:07 UTC, sdirix commented on packages/material-renderers/src/controls/MaterialDateControl.tsx
> +  const [focused, onFocus] = useFocus();
We lose the focus handling of `useFocus` here, i.e. it expects that `onBlur` is called at some point to remove the focus. Shouldn't we call the `onBlur` here in our custom `onBlur`?

2023-11-20 12:29 UTC, sdirix reviewed
one minor change request regarding the naming. besides that, look's good!

2023-11-20 12:29 UTC, sdirix commented on packages/material-renderers/src/util/datejs.tsx
> +    resetFocus: () => void
This method does not care why this callback is handed over. The parameter should be called `onBlur` or `callback`

2023-11-20 12:29 UTC, sdirix commented on packages/material-renderers/src/controls/MaterialTimeControl.tsx
> +  const updateChild = useCallback(() => setKey((key) => key + 1), [setKey]);
technically `setKey` is not required to be in the dependency list as it's guaranteed to be stable by React, however adding it doesn't break anything.

2023-12-13 12:00 UTC, sdirix requested changes
There is still some error lurking. To reproduce:

1. Open the React Material Ui example application ([link](https://deploy-preview-2200--jsonforms-examples.netlify.app/))
2. Into the `birthDate` field, enter the year 900. Observe that the `data` is not updated as intended because this year is invalid
3. Blur the field, e.g. by clicking into another one
4. Observe that the field is now empty, however the invalid date was saved into the data
5. Refocus the field and blur it again
6. Now the invalid date is actually removed from the data

Expected behavior:
After executing steps 1-3, the field and the actual data should be empty.

![DateErrors](https://github.com/eclipsesource/jsonforms/assets/8998368/dcffb769-5e59-4429-8908-f735eeffe168)

2023-12-20 12:02 UTC, LukasBoll commented
Hi @sdirix ,
this commit will change the default format of datetime to "YYYY-MM-DDTHH:mm:ss.sssZ," making it coherent with `convertDateToString` wich is used for `createDefaultValue` in the core.
The previous default format was the default format from dayjs (current date in ISO8601, without fraction seconds, e.g. '2020-04-02T08:02:17-05:00')
Is this fine or should we keep the old default format?

2023-12-20 12:39 UTC, sdirix commented
>Is this fine or should we keep the old default format?

This is fine as `sss` is also valid ISO8601

2024-01-09 18:18 UTC, LukasBoll commented on packages/material-renderers/src/controls/MaterialTimeControl.tsx
> +  const saveFormat = appliedUiSchemaOptions.timeSaveFormat ?? defaultTimeFormat;
The previous implementation didn’t support formats without seconds by default. So this wouldn't be an unexpected/new behavior. 
Currently I adjusted the examples in our application to use the `HH:mm:ss` format.
But it is also possible to check if the time-value uses the `HH:mm:ss` or `HH:mm` format and set the `saveFormat` accordingly. Would you prefer this solution?

2024-01-22 14:47 UTC, sdirix approved these changes
LGTM! Thanks

2024-01-22 14:48 UTC, merged