fix: resolve refs in EnumArrayRenderer
eclipsesource/jsonforms pull request #2204
Opened 2023-10-30 22:49 UTC by LukasBoll

resolve refs ind the MultiEnumControlProps mapper and tester

fixes #2192

2023-11-08 11:21 UTC, lucas-koehler requested changes
Hi @LukasBoll the changes look pretty good to me. There is one typo fix inline that also fixes the out of memory of the tests. I'm not sure why the typo led to an out of memory but it should not be related to this PR:
Likely it is ue to the implementation of `mapStateToMultiEnumControlProps`. However, I did not see anything obvious there. Furthermore, in a running application the method should never be invoked because the tester does not apply for effectively empty `items`. I tested this in the example material app and there simply a `No applicable renderer found.` is shown.

2023-11-13 13:22 UTC, LukasBoll commented on packages/core/test/util/renderer.test.ts
> +                ref$: '#/definitions/colors',
Oh, what a stupid mistake. The test is working now, thank you for taking a look @lucas-koehler !
I think the out of memory issues occurred in a view other test cases as well. 
So maybe there is an issue with one of the core functionalities, that is called by `mapStateToMultiEnumControlProps`.

2023-11-13 13:28 UTC, lucas-koehler commented on packages/core/test/util/renderer.test.ts
> +                ref$: '#/definitions/colors',
Yes, I am also aware of at least on other PR with out of memory issues. Thanks for the hint. However, we don't need to look at that in this PR :D

2023-11-13 13:28 UTC, lucas-koehler approved these changes
LGTM now! Thanks for the contribution :)

2023-11-13 13:30 UTC, merged