Vanilla TextCell password
eclipsesource/jsonforms pull request #2249
Opened 2024-01-11 08:53 UTC by adammation

The input type for a TextCell in the vanilla-renderers was 'text' and could not be changed.

This change keeps the default 'text' type but allows the type to be changed via an option "type"

`"options": {
              "type": "password"
            }`

See also:
https://jsonforms.discourse.group/t/input-type-with-vanilla-renderers/272

2024-01-11 08:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/eclipsesource/jsonforms?pullRequest=2249) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/eclipsesource/jsonforms?pullRequest=2249) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/eclipsesource/jsonforms?pullRequest=2249) it.</sub>

2024-01-11 10:24 UTC, sdirix requested changes
Hi! Thanks for the contribution :heart: 

In the React Material UI renderers we already support `format: 'password'` as the indicator to render a password field. Would this work for you too? I would prefer to be consistent between renderer sets.

2024-01-11 20:41 UTC, adammation commented
> Hi! Thanks for the contribution ❤️
> 
> In the React Material UI renderers we already support `format: 'password'` as the indicator to render a password field. Would this work for you too? I would prefer to be consistent between renderer sets.

Sounds great, changed to `format: "password"`

2024-01-22 12:32 UTC, sdirix requested changes

2024-01-22 12:32 UTC, sdirix commented on packages/vanilla-renderers/src/cells/TextCell.tsx
> +      }
```suggestion
      type={appliedUiSchemaOptions.format === 'password' ? 'password' : 'text'}
```

2024-01-22 12:33 UTC, sdirix commented on packages/vanilla-renderers/src/cells/TextCell.tsx
> +      }
I would prefer only passing through the password as in React Material. Other types might be incompatible. I would have applied the change myself but maintainer editing was turned off for this PR

2024-01-22 15:23 UTC, sdirix commented
Closed in favor of https://github.com/eclipsesource/jsonforms/pull/2254. Thanks for the contribution :heart:

2024-01-22 15:23 UTC, closed without merging

2024-01-22 16:33 UTC, adammation commented
Thanks @sdirix !