﻿refactor(core): resolve circular dependencies
eclipsesource/jsonforms pull request #2345
Opened 2024-06-11 12:52 UTC by LukasBoll

Eliminated circular dependencies in the core module and reorganized package structure.

Ref #2321

2024-06-14 13:08 UTC, lucas-koehler requested changes
Hi @LukasBoll , thanks for the PR :heart: 
The changes already look mostly good to me and no more circular dependency warnings are shown :)
Besides two inline comments, I suggest renaming the folder `stateToPropsMapper` to simply `mappers`: Not all of the methods are mapping state to props but most of them map either state or dispatch to some kind of props or utility data structure.

2024-06-29 08:54 UTC, LukasBoll commented on packages/core/src/jsonFormsCore/jsonFormsCore.ts
Yes, you are right, we don't need an extra module for this file, as it only fetches data from the store!

2024-06-29 08:57 UTC, LukasBoll commented
> Hi @LukasBoll , thanks for the PR ❤️ The changes already look mostly good to me and no more circular dependency warnings are shown :) Besides two inline comments, I suggest renaming the folder `stateToPropsMapper` to simply `mappers`: Not all of the methods are mapping state to props but most of them map either state or dispatch to some kind of props or utility data structure.

Hi @lucas-koehler,

Thank you for the review! I updated everything according to your suggestions!

2024-07-04 07:30 UTC, lucas-koehler approved these changes
Thanks for the updates @LukasBoll ! LGTM now :)

2024-07-04 07:31 UTC, merged