Feature/upgrade to angular 19
eclipsesource/jsonforms pull request #2395
Opened 2024-11-26 10:37 UTC by laurentgrangier

2024-11-27 14:57 UTC, lucas-koehler requested changes
Hi @laurentgrangier , thanks for this PR :heart: 
Many of the changes already look quite good. There are some minor comments inline.

One bigger issue seems to be the coverage reporting for the `angular-material` package. Executing `pnpm run test-cov` in the `angular-material` package no longer creates an lcov.info file. This is needed for coverage reports in PRs. You can see the expected result by executing tests on the main branch. For the `angular` package this still works.
My assumption is that there was some config in the deleted test-runner.js that configured this. Please have a look.

2024-12-02 13:13 UTC, laurentgrangier commented on packages/angular-material/angular.json
> +          "options": {
I added the options again. Thank you.

2024-12-02 13:14 UTC, laurentgrangier commented on packages/angular-material/angular.json
> +    },
You are right. I just copied them from the default generate file from Angular. I removed them.

2024-12-02 13:14 UTC, laurentgrangier commented on packages/angular-material/angular.json
> +  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
Done.

2024-12-02 13:15 UTC, laurentgrangier commented on packages/angular-material/package.json
>    "peerDependencies": {
I don't know. I don't remember removing them. But we can revert this remove. Thank you.

2024-12-02 13:16 UTC, laurentgrangier commented
> Hi @laurentgrangier , thanks for this PR ❤️ Many of the changes already look quite good. There are some minor comments inline.
> 
> One bigger issue seems to be the coverage reporting for the `angular-material` package. Executing `pnpm run test-cov` in the `angular-material` package no longer creates an lcov.info file. This is needed for coverage reports in PRs. You can see the expected result by executing tests on the main branch. For the `angular` package this still works. My assumption is that there was some config in the deleted test-runner.js that configured this. Please have a look.

The karma.config.js was missing in angular.json. Adding it properly should fix the missing lcov file. Can you please check? I'm not sure where I should see them in the build.

2024-12-02 15:00 UTC, lucas-koehler approved these changes
Hi @laurentgrangier ,
thanks for the updates. This LGTM now. Thanks for all your work :heart: 

I tested this locally with Angular 18 and 19 in the angular seed. Both worked fine :)

Regarding the code coverage: Executing the tests locally I could see that the code coverage files are now generated at expected location `packages/angular-materila/coverage/lcov.info`.
Apparently, there is another issue with the coverage report not being displayed in the PR as this is also the case for another, independent PR. Thus, nothing additional needs to be done here.

Note that I will close this PR and open a followup  one because we generally do not accept re-generated lock file contributions from third party contributors for security reasons. I could not push a re-generated one on your branch as this is disabled in your fork's settings. Thus, I'll push this to a branch here and open a new PR from there.

2024-12-02 15:05 UTC, lucas-koehler commented
Superseded by https://github.com/eclipsesource/jsonforms/pull/2403 . Thanks again @laurentgrangier  for this great PR :)

2024-12-02 15:05 UTC, closed without merging

2024-12-02 15:19 UTC, laurentgrangier commented
Thank you for the review and the new PR. 👍